name: marchmadness
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - pandas
  - numpy
  - tqdm
  - scikit-learn
  - pillow
  - seaborn
  - ipykernel
  - xgboost
  - tensorflow
  - jupyter
  - notebook
  - pip
  - pip:
    - shap
    - kaggle
    - yellowbrick


